/**
 * The estate's icon vocabulary, resolved to `MaterialIcons` (Google Material — the same family the
 * SPAs render through `@mui/icons-material`). Paper's `icon` prop defaults to MaterialCommunityIcons,
 * so `App.tsx` overrides the renderer via `settings={{ icon }}`; after that override every `icon=`
 * string must be a name from here. Pass `ICONS.x`, never a bare string — a wrong name renders
 * nothing at all rather than failing the build.
 */
export const ICONS = {
  account: 'account-circle',
  add: 'add',
  addCircle: 'add-circle',
  alert: 'error-outline',
  cake: 'cake',
  calendar: 'calendar-month',
  cancel: 'cancel',
  celebration: 'celebration',
  check: 'check',
  checkBox: 'check-box',
  checkCircle: 'check-circle',
  chevronLeft: 'chevron-left',
  chevronRight: 'chevron-right',
  cleaning: 'cleaning-services',
  clear: 'clear',
  close: 'close',
  contacts: 'contacts',
  delete: 'delete',
  email: 'email',
  event: 'event',
  expand: 'expand-more',
  filter: 'filter-list',
  folder: 'folder',
  folderOpen: 'folder-open',
  gridView: 'grid-view',
  group: 'group',
  heading: 'explore',
  help: 'help-outline',
  history: 'history',
  hotel: 'hotel',
  inbox: 'inbox',
  layers: 'layers',
  link: 'link',
  listView: 'view-list',
  locate: 'my-location',
  locateFixed: 'gps-fixed',
  locationOff: 'location-off',
  lock: 'lock',
  log: 'description',
  luggage: 'luggage',
  map: 'map',
  medical: 'medical-services',
  menu: 'menu',
  more: 'more-horiz',
  person: 'person',
  photos: 'photo-library',
  place: 'place',
  restaurant: 'restaurant',
  robot: 'smart-toy',
  run: 'directions-run',
  scan: 'document-scanner',
  schedule: 'schedule',
  search: 'search',
  settings: 'settings',
  share: 'share',
  sort: 'sort',
  star: 'star',
  starOutline: 'star-border',
  target: 'track-changes',
  tools: 'construction',
  tune: 'tune',
  walk: 'directions-walk',
} as const;

export type IconKey = keyof typeof ICONS;
