import { useAuth } from '../store/auth-store';

/**
 * Single-axis error class thrown for every non-2xx response. Consumers
 * downstream (e.g. the gallery's add-to-selection 409 handler) check
 * `err.status` to branch on specific HTTP codes — that contract stays the
 * same after the migration off the hand-typed client.
 */
export class ApiError extends Error {
  status: number;

  constructor(status: number, message: string) {
    super(message);
    this.status = status;
    this.name = 'ApiError';
  }
}

/**
 * Custom fetch invoked by every Orval-generated request. Returns the envelope `{ status, data, headers }` that
 * Orval's `client: 'react-query'` mode expects from a mutator; since the generator widens hook types as
 * `{ data: T; status: 200 } & { headers: Headers }`, consumers end up at `result.data?.data` — one `.data` from
 * react-query, one from this envelope. Same pattern LupiraWeb runs.
 *
 * Owns the base URL (read live from `useAuth.getState().mtgApiUrl`, so the settings-screen override is always
 * honoured), bearer injection, content-type handling, 204 → undefined data, and non-2xx → `ApiError`.
 */
type ApiEnvelope<T> = {
  status: number;
  data: T;
  headers: Headers;
};

export async function apiFetch<T>(
  url: string,
  init?: RequestInit,
): Promise<T> {
  const { mtgApiUrl, token } = useAuth.getState();
  if (!mtgApiUrl) {
    throw new ApiError(0, 'API base URL is not configured.');
  }

  const headers = new Headers(init?.headers ?? {});
  if (!headers.has('Accept')) {
    headers.set('Accept', 'application/json');
  }
  if (token && !headers.has('Authorization')) {
    headers.set('Authorization', `Bearer ${token}`);
  }
  // FormData sets its own multipart/form-data boundary — leave it alone.
  const isFormData =
    typeof FormData !== 'undefined' && init?.body instanceof FormData;
  if (init?.body && !isFormData && !headers.has('Content-Type')) {
    headers.set('Content-Type', 'application/json');
  }

  const fullUrl = mtgApiUrl.replace(/\/$/, '') + url;
  let res = await fetch(fullUrl, { ...init, headers });

  // Reactive re-auth: a 401 means the token was rejected (expired early / clock skew so the
  // proactive refresh never fired) and the request was NOT executed — safe to refresh once and
  // retry for any method. refreshIfNeeded owns the clear/keep decision: a definitive failure
  // clears the session (→ login) and returns null; a transient one keeps it and returns the same
  // token, so the 401 just surfaces and recovers on the next request. We pass the token actually
  // sent so a concurrent refresh isn't mistaken for a fresh one.
  if (res.status === 401 && token) {
    const fresh = await useAuth.getState().refreshIfNeeded({ force: true, sentToken: token });
    if (fresh && fresh !== token) {
      headers.set('Authorization', `Bearer ${fresh}`);
      res = await fetch(fullUrl, { ...init, headers });
    }
  }

  if (!res.ok) {
    const text = await res.text().catch(() => res.statusText);
    throw new ApiError(res.status, text || res.statusText);
  }

  let body: unknown;
  if (res.status === 204) {
    body = undefined;
  } else {
    const contentType = res.headers.get('content-type') ?? '';
    body = contentType.includes('application/json')
      ? await res.json()
      : await res.text();
  }

  const envelope: ApiEnvelope<unknown> = {
    status: res.status,
    data: body,
    headers: res.headers,
  };
  return envelope as T;
}

export default apiFetch;

/**
 * Coerce a `.NET decimal` field (`string | number`) to a number for display.
 * The OpenAPI spec generated by `Microsoft.AspNetCore.OpenApi` types every
 * `decimal` as `string | number` because System.Text.Json may serialise as
 * either depending on `JsonSerializerOptions.NumberHandling`. The mobile UI
 * always wants a number.
 *
 * Returns `NaN` for inputs that don't parse — callers can `Number.isFinite`
 * gate the display.
 */
export function asNumber(v: string | number | null | undefined): number {
  if (v == null) return Number.NaN;
  if (typeof v === 'number') return v;
  return Number(v);
}
