#!/usr/bin/env node
/**
 * Regenerates `src/ui/symbols/generated/symbolData.ts` from Scryfall's card-symbol list. Each SVG is
 * converted to a node tree ahead of time so the app renders it with react-native-svg primitives
 * without parsing XML while lists scroll.
 */
import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const outFile = path.resolve(__dirname, '..', 'src', 'ui', 'symbols', 'generated', 'symbolData.ts');

// Scryfall asks API clients to identify themselves and stay under 10 requests/second.
const headers = { 'User-Agent': 'LupiraMtgMobile/1.0', Accept: 'application/json' };
const SUPPORTED_TAGS = new Set(['svg', 'g', 'path', 'circle']);
const DROPPED_ATTRS = new Set(['xmlns', 'id', 'viewBox']);

async function get(url, as) {
  const res = await fetch(url, { headers });
  if (!res.ok) throw new Error(`${res.status} ${res.statusText} from ${url}`);
  return as === 'json' ? res.json() : res.text();
}

const camel = (name) => name.replace(/-([a-z])/g, (_, ch) => ch.toUpperCase());

function parseSvg(xml, symbol) {
  const root = { children: [] };
  const stack = [root];
  let viewBox = null;
  for (const [, closing, tag, rawAttrs, selfClosing] of xml.matchAll(/<(\/?)([a-zA-Z]+)([^>]*?)(\/?)>/g)) {
    if (closing) {
      stack.pop();
      continue;
    }
    if (!SUPPORTED_TAGS.has(tag)) throw new Error(`${symbol}: unsupported <${tag}>`);
    const attrs = {};
    for (const [, name, , value] of rawAttrs.matchAll(/([\w:-]+)=(['"])(.*?)\2/g)) {
      if (tag === 'svg' && name === 'viewBox') viewBox = value;
      if (!DROPPED_ATTRS.has(name)) attrs[camel(name)] = value;
    }
    const node = { t: tag, a: attrs, c: [] };
    stack.at(-1).children.push(node);
    if (!selfClosing) stack.push({ node, children: node.c });
  }
  const svg = root.children[0];
  if (!svg || svg.t !== 'svg' || !viewBox) throw new Error(`${symbol}: no <svg viewBox>`);
  return { viewBox, nodes: svg.c.map(prune) };
}

function prune({ t, a, c }) {
  const node = { t };
  if (Object.keys(a).length) node.a = a;
  if (c.length) node.c = c.map(prune);
  return node;
}

const { data } = await get('https://api.scryfall.com/symbology', 'json');
const entries = [];
for (const s of data) {
  const code = s.symbol.slice(1, -1);
  const { viewBox, nodes } = parseSvg(await get(s.svg_uri, 'text'), s.symbol);
  entries.push([code, { label: s.english, viewBox, nodes }]);
  await new Promise((r) => setTimeout(r, 100));
}

const body = entries.map(([code, def]) => `  ${JSON.stringify(code)}: ${JSON.stringify(def)},`).join('\n');
await fs.mkdir(path.dirname(outFile), { recursive: true });
await fs.writeFile(
  outFile,
  `// Generated by scripts/fetch-symbols.mjs from https://api.scryfall.com/symbology. Do not edit.\n` +
    `import type { SymbolDef } from '../SymbolDef';\n\n` +
    `export const SYMBOLS: Record<string, SymbolDef> = {\n${body}\n};\n`,
);
console.log(`Wrote ${entries.length} symbols → ${outFile}`);
